version: 2
jobs:
  build:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Dialyzer
          command: rebar3 compile
  dialyzer:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Dialyzer
          command: rebar3 dialyzer
  ct:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Common Tests
          command: rebar3 ct -v
  eunit:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Eunit
          command: rebar3 eunit
  xref:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Xref
          command: rebar3 xref
workflows:
  version: 2
  tests:
    jobs:
      - dialyzer
      - ct
      - eunit
