version: 2
jobs:
  build:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Compile
          command: rebar3 compile
  test:
    docker:
      - image: erlang:19
    requires:
        - build
    steps:
      - checkout
      - run:
          name: Common Tests
          command: rebar3 ct -v
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
