version: 2
jobs:
  build:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Builder
          command: rebar3 compile
  dialyzer19:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Dialyzer
          command: rebar3 dialyzer
  dialyzer20:
    docker:
      - image: erlang:20
    steps:
      - checkout
      - run:
          name: Dialyzer
          command: rebar3 dialyzer
  ct19:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Common Tests
          command: rebar3 ct -v
  ct20:
    docker:
      - image: erlang:20
    steps:
      - checkout
      - run:
          name: Common Tests
          command: rebar3 ct -v
  eunit19:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Eunit
          command: rebar3 eunit
  eunit20:
    docker:
      - image: erlang:20
    steps:
      - checkout
      - run:
          name: Eunit
          command: rebar3 eunit
  xref19:
    docker:
      - image: erlang:19
    steps:
      - checkout
      - run:
          name: Xref
          command: rebar3 xref
  xref20:
    docker:
      - image: erlang:20
    steps:
      - checkout
      - run:
          name: Xref
          command: rebar3 xref
workflows:
  version: 2
  tests:
    jobs:
      - dialyzer19
      - ct19
      - eunit19
      - xref19
      - dialyzer20
      - ct20
      - eunit20
      - xref20
